src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnnonceRepository::class)
 */
class Annonce
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description_courte;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description_longue;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="annonces")
     */
    private $categorie;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_enregistrement;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="annonces")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Media::class, mappedBy="annonce")
     */
    private $media;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="annonce")
     */
    private $commentaires;

    public function __construct()
    {
        $this->media = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescriptionCourte(): ?string
    {
        return $this->description_courte;
    }

    public function setDescriptionCourte(?string $description_courte): self
    {
        $this->description_courte = $description_courte;

        return $this;
    }

    public function getDescriptionLongue(): ?string
    {
        return $this->description_longue;
    }

    public function setDescriptionLongue(?string $description_longue): self
    {
        $this->description_longue = $description_longue;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCategorie(): ?categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(?\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Media[]
     */
    public function getMedia(): Collection
    {
        return $this->media;
    }

    public function addMedium(Media $medium): self
    {
        if (!$this->media->contains($medium)) {
            $this->media[] = $medium;
            $medium->setAnnonce($this);
        }

        return $this;
    }

    public function removeMedium(Media $medium): self
    {
        if ($this->media->removeElement($medium)) {
            // set the owning side to null (unless already changed)
            if ($medium->getAnnonce() === $this) {
                $medium->setAnnonce(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setAnnonce($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getAnnonce() === $this) {
                $commentaire->setAnnonce(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->id;
    }
}

src/Form/AnnonceType.php
<?php

namespace App\Form;
use App\Entity\Media;
use App\Entity\Annonce;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\FileType;

class AnnonceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre')
            ->add('description_courte')
            ->add('description_longue')
            ->add('prix')
            ->add('adresse')
            ->add('cp')
            ->add('ville')
            ->add('categorie')
            ->add('media', FileType::class, [
                "multiple" => true,
                "mapped" => false,
                "required" => false,

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Annonce::class,
        ]);
    }
}

src/Controller/AnnonceController.php
<?php

namespace App\Controller;

use App\Entity\Annonce;
use App\Entity\Media;
use App\Form\AnnonceType;
use App\Repository\AnnonceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/annonce')]
class AnnonceController extends AbstractController
{
    #[Route('/', name: 'annonce_index', methods: ['GET'])]
    public function index(AnnonceRepository $annonceRepository): Response
    {
        return $this->render('annonce/index.html.twig', [
            'annonces' => $annonceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'annonce_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $annonce = new Annonce();
        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $annonce->setDateEnregistrement(new \DateTimeImmutable('now'));
            $user = $this->getUser();
            $annonce->setUser($user);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($annonce);
            $entityManager->flush();

            $mediaFile = $form->get('media')->getData();

            if($mediaFile){
                for ($i=0; $i < count($mediaFile); $i++){
                    $media = new Media;

                    $nomMedia = date("TmdHis") . "-" . uniqid() . "-" . $mediaFile[$i]->getClientOriginalName();

                    $mediaFile[$i]->move(
                        $this->getParameter("media_annonce"),
                        $nomMedia
                    );

                    $media->setNom($nomMedia);
                    $media->setAnnonce($annonce);
                    $type = "image";
                    $media->setType($type);

                    $entityManager->persist($media);
                    $entityManager->flush();
                }
            }
            $this->addFlash("success", "L'annonce n°  a bien été ajoutée");
            return $this->redirectToRoute('annonce_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('annonce/new.html.twig', [
            'annonce' => $annonce,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'annonce_show', methods: ['GET'])]
    public function show(Annonce $annonce): Response
    {
        return $this->render('annonce/show.html.twig', [
            'annonce' => $annonce,
        ]);
    }

    #[Route('/{id}/edit', name: 'annonce_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Annonce $annonce): Response
    {
        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('annonce_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('annonce/edit.html.twig', [
            'annonce' => $annonce,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'annonce_delete', methods: ['POST'])]
    public function delete(Request $request, Annonce $annonce): Response
    {
        if ($this->isCsrfTokenValid('delete'.$annonce->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($annonce);
            $entityManager->flush();
        }

        return $this->redirectToRoute('annonce_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/annonce/_delete_form.html.twig
<form method="post" action="{{ path('annonce_delete', {'id': annonce.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ annonce.id) }}">
    <button class="btn">Delete</button>
</form>

templates/annonce/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Annonce{% endblock %}

{% block body %}
    <h1>Edit Annonce</h1>

    {{ include('annonce/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('annonce_index') }}">back to list</a>

    {{ include('annonce/_delete_form.html.twig') }}
{% endblock %}

templates/annonce/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonce index{% endblock %}

{% block body %}
    <h1>Annonce index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Description_courte</th>
                <th>Description_longue</th>
                <th>Prix</th>
                <th>Adresse</th>
                <th>Cp</th>
                <th>Ville</th>
                <th>Date_enregistrement</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for annonce in annonces %}
            <tr>
                <td>{{ annonce.id }}</td>
                <td>{{ annonce.titre }}</td>
                <td>{{ annonce.descriptionCourte }}</td>
                <td>{{ annonce.descriptionLongue }}</td>
                <td>{{ annonce.prix }}</td>
                <td>{{ annonce.adresse }}</td>
                <td>{{ annonce.cp }}</td>
                <td>{{ annonce.ville }}</td>
                <td>{{ annonce.dateEnregistrement ? annonce.dateEnregistrement|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('annonce_show', {'id': annonce.id}) }}">show</a>
                    <a href="{{ path('annonce_edit', {'id': annonce.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('annonce_new') }}">Create new</a>
{% endblock %}

templates/annonce/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Annonce{% endblock %}

{% block body %}
    <h1>Create new Annonce</h1>

    {{ include('annonce/_form.html.twig') }}

    <a href="{{ path('annonce_index') }}">back to list</a>
{% endblock %}

templates/annonce/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonce{% endblock %}

{% block body %}
    <h1>Annonce</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ annonce.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ annonce.titre }}</td>
            </tr>
            <tr>
                <th>Description_courte</th>
                <td>{{ annonce.descriptionCourte }}</td>
            </tr>
            <tr>
                <th>Description_longue</th>
                <td>{{ annonce.descriptionLongue }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ annonce.prix }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ annonce.adresse }}</td>
            </tr>
            <tr>
                <th>Cp</th>
                <td>{{ annonce.cp }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ annonce.ville }}</td>
            </tr>
            <tr>
                <th>Date_enregistrement</th>
                <td>{{ annonce.dateEnregistrement ? annonce.dateEnregistrement|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

        <div class="col-md-4 mt-5">
            <div class="row">
                {% for media in annonce.media %}
                    <img src="{{ asset("media/mediaUpload/" ~ media.nom ) }}" alt="" style="width:200px">

                {% endfor %}
            </div>
        </div>

        <div>
            
			<h4>Commentaires</h4>
			{% if annonce.commentaires %}
			{% for commentaire in annonce.commentaires %}
			<p>{{ commentaire.user.pseudo}} :-   {{ commentaire.commentaire }}</p>
				
			{% endfor %}
			{% endif %}
        </div>


    <a href="{{ path('commentaire_new', {'id': annonce.id}) }}">Create new comment</a> 

    <a href="{{ path('annonce_index') }}">back to list</a>

    <a href="{{ path('annonce_edit', {'id': annonce.id}) }}">edit</a>

    {{ include('annonce/_delete_form.html.twig') }}
{% endblock %}